kind: pipeline
type: docker
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: chluehr/playwright
    auto_tag: true
    tags:
      - latest
      - '1.49-1'
      - '1-1'
    username: 
        from_secret: docker_username
    password: 
        from_secret: docker_password


