kind: pipeline
type: docker
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: chluehr/playwright
    tags:
      - latest
      - '1.49-1.0.0'
      - '1-1.0.0'
    username: 
        from_secret: docker_username
    password: 
        from_secret: docker_password


